### ISSUE TITLE
Stereo render is broken (Build v2.09.65).

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#39]
I tried to test a new update and how render of shadow is working now, in "Volta 1: The Stone".

When I look ahead, do not see any problems, but if I try to observe surroundings and turn my view in left or right, than stereo render behavior is changing.

Normally, "stereo picture" means "move a view position to the left and create picture to the left eye, and move to the right and create picture to the right eye".
But now, with a wrong render, it's working like "move a view position to the UP DIRECTION and create picture to the left eye, and move to the DOWN DIRECTION and сreate picture to the right eye".
I do not tested further cause it's painful to my eyes. I just roll back to the old build (v2.09.61).

Check view pos "552.59 5499.43 -923.75 -0.0 -7.7 -0.0". This place have the bench (Look to right) and this bench have a very contrast moss stains on the surface, so it's easy to see what is wrong. 
(It's just an example. I see this wrong render everywhere, of course).

Also, issue https://github.com/fholger/thedarkmodvr/issues/38 are not resolved. Now whole room is disappearing. Light sources will disappear first and the whole room after that.

**Comment by fholger** [comment]
I'm afraid you picked a bad time to test the nightly build, because I'm in the process of reworking some math, and I'm not finished with it... Either pick build 62 before those changes (https://ci.appveyor.com/project/fholger/thedarkmodvr/builds/34601083), or switch to the OpenXR backend, as that one should not be affected. (At least not from the stereo bug, it might still be affected by incorrect culling)

**Comment by LaoGaoBeBePao** [comment]
Ok, got it, thanks.

Do I need to write about a new issues that I found or just wait? As an example, spyglass also not working properly, at some viewpos I see only the sky / level background.

**Comment by fholger** [comment]
In general, nightly builds should be considered unstable, so issues are expected. I don't mind you reporting them, in fact it can be helpful to be made aware of potential issues early. Of course, the more obvious the bug is the more like it is I'm already aware of it.
It's really up to you how much time you want to spend on testing unstable builds :)

As for the spyglass, if it's working in alpha5, then it's certainly related to the current changes. But if you put the viewpos here, I can make sure it'll be fixed by the time alpha6 is released.

**Comment by LaoGaoBeBePao** [comment]
Resolved in v2.09.66.

**Comment by LaoGaoBeBePao** [comment]
Problem is solved in v2.09.66.

**Comment by fholger** [comment]
Thanks for the confirmation!

**Comment by LaoGaoBeBePao** [comment]
YOU WELCOME
