### ISSUE TITLE
gl4stereo - linux compiling

### ISSUE THREAD

**Issue by Olm-e** [fholger/thedarkmodvr#6]
hi
the vr/Framebuffer.h need <GL/gl.h> not <gl/GL.h> to compile on linux
after that we now get 

renderer/gl4/OcclusionSystem.h: At global scope:
renderer/gl4/OcclusionSystem.h:36:13: error: extra qualification ‘OcclusionSystem::’ on member ‘ReserveOccluders’ [-fpermissive]
  Occluder * OcclusionSystem::ReserveOccluders( uint count );

--

side note : I would suggest to look at the Doom3BFG-VR implementation for a successfull one 
(I don't know the details but it works great on win and linux, - except for the VR controllers for some reasons on linux... )
https://github.com/ChristophHaag/DOOM-3-BFG-VR

**Comment by fholger** [comment]
Hi,

I am aware of both the VR ports for Doom 3, and I did look at them and based the basics of my implementation on them. Unfortunately, they are both based on the BFG release of Doom 3, whereas TDM is based on the older original Doom3 engine, and unfortunately, there are very significant changes to the renderer in BFG. So a straight port is impossible, and TDM has its own unique issues to solve, particularly performance-wise, before I can really advance the VR port.

This also means that at the moment, the VR port is in a transitioning stage. I have investigated a lot of paths to improve the performance and found some things that are vital and really help, but they are not currently stable. And for the sake of my own sanity, I need to port some of these changes back to the TDM project before advancing further, because otherwise maintaining this port is going to become a nightmare. While it is in this transitioning state, I'm afraid that Linux support has to remain an after-thought. There will be a lot of iterations with breaking changes, and I do all of the development work on a Windows machine. So I think fixing the Linux build only makes sense once the major rendering overhaul is complete and at least somewhat stable, otherwise it's going to cost a lot of extra effort. You are not currently missing much, though. Current master still has a lot of rendering issues :)
